# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be59e14e189c49742b23d4698f06948bc85ee78d9fe4b6079a241b70c536372d6d4094cd34979a7e7f68a1905cb92a4d346a2764a797676eb5486bf5bc6ba434

test:
  secret_key_base: 167e33ad23def5d435810744ca53005f8f31861a6da08800d8a227515400ee2632ab6ad01a30dcec56251fe144cb4df2ce84838fd0154765c57edba61d4a6c34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
